<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Click verify once there are none left_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>ca081b0e-ee78-478f-99eb-3421d2d8efe0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0d352761-4bda-4ff6-8dd5-aa6368422893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>c02c7349-4710-4b94-977f-665a181a90b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AL8dmw8hpod262W-exMhD_GSHPsIddxNTZKxPu7_yl8H17yjdwzVxLvY7iCOkoWj7MNVyvABhqn8TyfpNmQSQSg9lhGv4_42Ffsh1C2EkMPvuopk-UHT3fpXjzStaEW4QJ6PmRd_sh3m72YWxHbUSJXbOS1oLn5X0fWuPbb0KdFyQQxqTZUcxErqrtzIBRsqAe1hCsoCTIvbQLY4JRwbAGQT1cO9EzR40w&amp;k=6LdsKacZAAAAAIxY1X8GuHZljebmKWs8JGp97UK7</value>
      <webElementGuid>5c84967b-1a9b-419c-a64d-165b7e435180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>e7e9613a-7ebe-4f8c-aac9-0398162f8752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/demoQA/Page_DEMOQA/Page_DEMOQA/iframe_html1body1div5div4iframe1_c-fr9359ssa6ge</value>
      <webElementGuid>74af1dc4-b7ea-4e6a-8ce0-d66f757ec41e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      <webElementGuid>20cde388-5c76-401e-8236-f68b91de98ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AL8dmw8hpod262W-exMhD_GSHPsIddxNTZKxPu7_yl8H17yjdwzVxLvY7iCOkoWj7MNVyvABhqn8TyfpNmQSQSg9lhGv4_42Ffsh1C2EkMPvuopk-UHT3fpXjzStaEW4QJ6PmRd_sh3m72YWxHbUSJXbOS1oLn5X0fWuPbb0KdFyQQxqTZUcxErqrtzIBRsqAe1hCsoCTIvbQLY4JRwbAGQT1cO9EzR40w&amp;k=6LdsKacZAAAAAIxY1X8GuHZljebmKWs8JGp97UK7')])[5]</value>
      <webElementGuid>24e4e287-96f5-4564-bf1e-7671673f9db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/img</value>
      <webElementGuid>80fbbcff-8db0-48af-841a-715265f1494b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AL8dmw8hpod262W-exMhD_GSHPsIddxNTZKxPu7_yl8H17yjdwzVxLvY7iCOkoWj7MNVyvABhqn8TyfpNmQSQSg9lhGv4_42Ffsh1C2EkMPvuopk-UHT3fpXjzStaEW4QJ6PmRd_sh3m72YWxHbUSJXbOS1oLn5X0fWuPbb0KdFyQQxqTZUcxErqrtzIBRsqAe1hCsoCTIvbQLY4JRwbAGQT1cO9EzR40w&amp;k=6LdsKacZAAAAAIxY1X8GuHZljebmKWs8JGp97UK7']</value>
      <webElementGuid>e4029722-dab6-4d17-b87c-3246abfb74f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
