<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_motorcycles_rc-image-tile-44</name>
   <tag></tag>
   <elementGuidId>05d791cc-d7e4-4bb5-a1fd-797da1d73216</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c9a875b0-e193-46c6-ba94-f7e81b3d7dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>fe4f525e-6c76-4eac-b0c7-419dccd940a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AL8dmw9U2kBhBWb0EKoNzUOhpZjgX6M8EWAyo5PKt723gUhhD5nlqKbwhhm51sHwh_y_zubXtRXSKA0VfPwbOggTwFMdX3s_AciueQRkCMXERTkYR36BV0SrXrJrD9f-il-wwgNgT8HO7-nNGyuj4L9QZrYrmGRlL1K0TbgVD-JUHyY-No7f0VWBTctKBCjWA6E1Wxn2G9NKeZbCEF7Mr9s6j2STKZkYbg&amp;k=6LdsKacZAAAAAIxY1X8GuHZljebmKWs8JGp97UK7</value>
      <webElementGuid>8ac0a8b0-2c55-46bd-b0f0-4128dd69cfe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>6a910585-0703-4812-9f68-46da28e991dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/demoQA/Page_DEMOQA/iframe_html1body1div5div4iframe1_c-gkwvmabs0094</value>
      <webElementGuid>15f6aefb-feae-41c8-8893-8dc88716cefd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[4]/div/div/img</value>
      <webElementGuid>fa667a18-feac-4b03-a72b-d7def348787c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AL8dmw9U2kBhBWb0EKoNzUOhpZjgX6M8EWAyo5PKt723gUhhD5nlqKbwhhm51sHwh_y_zubXtRXSKA0VfPwbOggTwFMdX3s_AciueQRkCMXERTkYR36BV0SrXrJrD9f-il-wwgNgT8HO7-nNGyuj4L9QZrYrmGRlL1K0TbgVD-JUHyY-No7f0VWBTctKBCjWA6E1Wxn2G9NKeZbCEF7Mr9s6j2STKZkYbg&amp;k=6LdsKacZAAAAAIxY1X8GuHZljebmKWs8JGp97UK7')])[12]</value>
      <webElementGuid>f5e7fad4-ecae-45fe-a1cc-174fe14cfef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]/div/div/img</value>
      <webElementGuid>db0b32e7-1048-4768-843d-f1fe23ff9f2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AL8dmw9U2kBhBWb0EKoNzUOhpZjgX6M8EWAyo5PKt723gUhhD5nlqKbwhhm51sHwh_y_zubXtRXSKA0VfPwbOggTwFMdX3s_AciueQRkCMXERTkYR36BV0SrXrJrD9f-il-wwgNgT8HO7-nNGyuj4L9QZrYrmGRlL1K0TbgVD-JUHyY-No7f0VWBTctKBCjWA6E1Wxn2G9NKeZbCEF7Mr9s6j2STKZkYbg&amp;k=6LdsKacZAAAAAIxY1X8GuHZljebmKWs8JGp97UK7']</value>
      <webElementGuid>2a753afe-09cc-42e3-ac07-856f6e83f31e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
