<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>drag-drop-upload</name>
   <tag></tag>
   <elementGuidId>d9589d31-9e4e-4ca5-b5ea-07211071a8a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#drag-drop-upload</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='drag-drop-upload']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c11977b3-a590-4d97-8b3a-72f72bc166f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dz-success-mark dz-clickable</value>
      <webElementGuid>1c692f78-1699-4511-a1bb-bb8129c9fc28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drag-drop-upload</value>
      <webElementGuid>493d91c7-2472-4b73-abc6-3d963a1a0d23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drag-drop-upload&quot;)</value>
      <webElementGuid>ea5497de-5ae0-4190-b598-436050ba9dc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='drag-drop-upload']</value>
      <webElementGuid>0a2be74b-ceb5-4a99-b23c-ae5d5286e15f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]</value>
      <webElementGuid>3d398399-41bb-4918-8fa5-348e7e9a44d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='File Uploader'])[1]/following::div[1]</value>
      <webElementGuid>b0dcca15-edec-4ead-949a-472e599c5897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='✔'])[1]/preceding::div[3]</value>
      <webElementGuid>a7c90a71-d866-40c1-8c72-9b126e1ef08d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>21cf2734-2f47-498c-a01b-3e1790c98645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'drag-drop-upload']</value>
      <webElementGuid>d5a0ec3d-bf3f-429c-93b4-8bfb21202bad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
